spring:
  application:
    name: goodbye-service

server:
  port: 8102

eureka:
  instance:
    metadataMap:
      zone: zoneB
    hostname: localhost
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8004/eureka