spring:
  application:
    name: hello-service

server:
  port: 8100

eureka:
  instance:
    metadataMap:
      zone: zoneA
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8003/eureka
    registry-fetch-interval-seconds: 2